// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2oJdloeko4kJYSlLY7JFMuZh2RMcoFfg',
    appId: '1:711704239286:android:fab3561601d932493d5a17',
    messagingSenderId: '711704239286',
    projectId: 'travelpoint-390316',
    storageBucket: 'travelpoint-390316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSRnF4OUnfTTBursFS1QGVvwYIHDIkDo',
    appId: '1:711704239286:ios:974f5737b0d2cab63d5a17',
    messagingSenderId: '711704239286',
    projectId: 'travelpoint-390316',
    storageBucket: 'travelpoint-390316.appspot.com',
    iosClientId: '711704239286-44gjona594eoe2uggmo5lrndi4k2ta6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLSRnF4OUnfTTBursFS1QGVvwYIHDIkDo',
    appId: '1:711704239286:ios:a6da0ea390bf44a23d5a17',
    messagingSenderId: '711704239286',
    projectId: 'travelpoint-390316',
    storageBucket: 'travelpoint-390316.appspot.com',
    iosClientId: '711704239286-m1504lemgii9hfj8c10ul4oltrvk9mfc.apps.googleusercontent.com',
    iosBundleId: 'com.travelpoint.app',
  );
}
